<a href="https://colab.research.google.com/github/MP-cod/PyTorch-fundamentals-25-hours-workshop-/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Python Fundamentals

In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduction to Tensors

### Ceating tensors

Pytorch tensors are created using `torch.Tensor()`=https://pytorch.org/docs/stable/torch.html#tensors

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Get Tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor
TENSOR= torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

##Random tensors

why random tensors/

Random tensors are impirtant because the way many neural network learn is that they start with tensors and adjust those random numbers to better represent the data.



```
# Start with random numbers -> look at data -> update random numbers -> look at data -> update data
```
Torch random tensors - [Pytorch doc](https://https://pytorch.org/docs/stable/generated/torch.rand.html)


In [ ]:
##Create a random Tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.3705, 0.5702, 0.4146, 0.2880],
        [0.4336, 0.9878, 0.9467, 0.3954],
        [0.8221, 0.2900, 0.4715, 0.2830]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_img_size_tensor=torch.rand(size=(3,224,224)) #height, width, colour channel (R,G,B)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.9878, 0.6700, 0.4115],
        [0.3893, 0.6454, 0.7413],
        [0.4803, 0.3225, 0.5661]])

##Zeroes & ones

In [ ]:
#Create a tensor of all zeroes
zeroes=torch.zeros(size=(3,
                        4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensord and tensors-like

In [ ]:
# use torch.arange()
one_to_ten=torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeroes=torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatype

**Note:** Tensor datatype is one of the 3 big issues/errors you'll run into Pytorch & DL:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the same device

[Precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)






In [ ]:
#Float 32 tensor
float32_tensor=torch.tensor([3.0,6.0,9.0], dtype=None, #what datatype is the tensor(eg. float32 or float16)
                            device=None, #What device is your tensor on
                            requires_grad=False) # whether or not to track gradients
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
torch16_tensor=float32_tensor.type(torch.float16)
torch16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
torch16_tensor*float32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### getting info from Tensors
1. Tensors not right datatype - to get datatype from a tensor, can use `'tensor.dtype'`
2. Tensors not right shape- to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the same device- to get device from a tensor, can use `tensor.device`





In [ ]:
### Create a tensor
some_tensor=torch.rand(3,4)
some_tensor


tensor([[0.7384, 0.4999, 0.6869, 0.7473],
        [0.7351, 0.9391, 0.8742, 0.1862],
        [0.5497, 0.4435, 0.5714, 0.9399]])

In [ ]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatypr of tensor:  {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7384, 0.4999, 0.6869, 0.7473],
        [0.7351, 0.9391, 0.8742, 0.1862],
        [0.5497, 0.4435, 0.5714, 0.9399]])
Datatypr of tensor:  torch.float32
shape of tensor: torch.float32
Device tensor is on: cpu


### Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication




In [ ]:
#create a tensor
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor*10


tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

Two main ways of performing multiplication in neural networks & DL:


1.   Element-wise multiplication
2.   Matrix multiplication(dot product)

More info on multiplying matrices-(refer my notebook under construction)

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3,2) @ (3,2)`won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`




In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [ ]:
#Element wise multiplication
print(tensor, "*" ,tensor)
print(f"equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.93 ms, sys: 979 µs, total: 2.91 ms
Wall time: 2.99 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 986 µs, sys: 0 ns, total: 986 µs
Wall time: 906 µs


tensor(14)

###One of the biggest errors in DL: shape errors


In [ ]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
#the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A= {tensor_A.shape}, tensor_B= {tensor_B.shape}")
print(f"New shape: tensor_A= {tensor_A.shape}, (same shape as above), tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output= torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A= torch.Size([3, 2]), tensor_B= torch.Size([3, 2])
New shape: tensor_A= torch.Size([3, 2]), (same shape as above), tensor_B.T= torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


##Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
#create a tensor
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# find the mean- note the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the positito n in tensor that has the min value with argmin()-> returns the index of tensor where the min value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping- reshapes an input tensor to a defined shape
* View- return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stack- combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze- removes all `1` dimensions from tensor
* Unsqueeze- add a `1` dimension to the target tensor
* Permute- return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
#let's create a tensor
xy=torch.arange(1.,10.)
xy, xy.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
xy_reshaped=xy.reshape(1,7)
xy_reshaped, xy_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
xy_reshaped=xy.reshape(1,9)
xy_reshaped, xy_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
xy_reshaped=xy.reshape(9,1)
xy_reshaped, xy_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
xy2=torch.arange(1,13)
xy2, xy2.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
xy2_reshape=xy2.reshape(4,3)
xy2_reshape

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
#change the view
z=xy.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x(because a view of a tensor shares the same memory as the original tensor)
z[:, 0]=5
z,xy

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other
xy_stacked=torch.stack([xy,xy,xy,xy], dim=1)
xy_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#torch.squeeze()- removes all single dimensions from a target tensor
xy_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
xy_reshaped.shape

torch.Size([9, 1])

In [ ]:
xy_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
xy_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f"previous tensor: {xy_reshaped}")
print(f"pevious shape: {xy_reshaped.shape}")

#remove extra dimensions from xy_reshaped
xy_squeezed=xy_reshaped.squeeze()
print(f"\nNew Tensor: {xy_squeezed}")
print(f"New shape: {xy_squeezed.shape}")

previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
pevious shape: torch.Size([9, 1])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze()- adds a single dim at specific dim in the target tensor
print(f"previous target: {xy_squeezed}")
print(f"previous shape: {xy_squeezed.shape}")

#add an extra dim with unsqueeze
x_unsqueezed=xy_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")


previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [ ]:
# torch.permute- rearranges the dimensions of a target tensor in a specialised order
x_original=torch.rand(size=(224,224,3)) #[height, width, color_channels]

# permute the original tensor to reaarange the axis (or dim)
x_permuted=x_original.permute(2,0,1) #shapes axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]


previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.1398, 0.8753, 0.0735],
         [0.0321, 0.0177, 0.6925],
         [0.7439, 0.9163, 0.3932],
         ...,
         [0.6722, 0.4245, 0.6289],
         [0.3449, 0.9861, 0.5737],
         [0.8528, 0.5797, 0.8360]],

        [[0.1948, 0.0063, 0.0948],
         [0.0640, 0.0874, 0.6470],
         [0.2783, 0.1828, 0.0954],
         ...,
         [0.6779, 0.3825, 0.1397],
         [0.0155, 0.4187, 0.4822],
         [0.6230, 0.7133, 0.5760]],

        [[0.7561, 0.9380, 0.5629],
         [0.2613, 0.3859, 0.1403],
         [0.6866, 0.3716, 0.0233],
         ...,
         [0.9392, 0.4986, 0.3575],
         [0.7218, 0.4663, 0.0755],
         [0.4886, 0.2066, 0.6765]],

        ...,

        [[0.5387, 0.2688, 0.9266],
         [0.8410, 0.8834, 0.9399],
         [0.1718, 0.7021, 0.1335],
         ...,
         [0.5745, 0.3817, 0.1637],
         [0.6029, 0.2232, 0.1746],
         [0.6074, 0.9538, 0.8074]],

        [[0.5739, 0.9352, 0.5500],
         [0.7325, 0.2238, 0.6747],
         [0.

In [ ]:
x_original[0,0,0]=728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

##Indexing(selecting data from tensors)

indexing with PyTorch is similar indexing with NumPy



In [ ]:
#create a tensor
h=torch.arange(1,10).reshape(1,3,3)
h, h.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#let's index on our new tensor
h[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#let's index on the middle bracket(dim=1)
h[0][0]

tensor([1, 2, 3])

In [ ]:
#let's index on the most inner bracket (last dimension)
h[0][0][0]

tensor(1)

In [ ]:
h[1][1][1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
h[0][1][1]

tensor(5)

In [ ]:
h[0][2][2]

tensor(9)

In [ ]:
#you can also use ":" to selct "all" of a target dimension
h[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all values of 0th dim and 1st dim but only index 1 of 2nd dim
h[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of 0th dim but only index 1st and 2nd dim
h[:, 1,1]

tensor([5])

In [ ]:
#get index 0 of the 0th dim and all values of 2nd dim
h[0,0,:]

tensor([1, 2, 3])

In [ ]:
#index on h to return 9
h[:,2,2]
#index on h to return 3,6,9
h[:,:,2]

tensor([[3, 6, 9]])

## pytorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor ->`torch.from_numpy(ndarray)`

* PyTorch tensor-> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#NumPy array to tensor
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32) #warning: when converting from numpy-> pytorch, pytorch reflects numpy's default datatype of float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
torch.arange(1.0,8.0).dtype #PyTorch's default data type

torch.float32

In [ ]:
#Change the value of array, what will this do to `tensor`?
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor what happens to numpy tensor
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random)

In short how a neural network learns:

`start with random numbers-> tensor operations -> update random numbers to try and make them better representations of the data-> again -> again -> again...`

to reduce the randomness in neural network & Pytorch comes the concept of **random seed**
Essentially what the random seed does is "flavour" the randomness.


In [ ]:
torch.rand(3,3)

tensor([[0.3691, 0.8400, 0.8488],
        [0.7169, 0.5915, 0.0656],
        [0.5753, 0.7282, 0.1347]])

In [ ]:
#create two random tensors
random_tensorA=torch.rand(3,4)
random_tensorB=torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.2398, 0.8952, 0.9808, 0.4215],
        [0.4663, 0.4111, 0.1015, 0.9980],
        [0.0176, 0.2957, 0.1054, 0.8482]])
tensor([[0.8391, 0.6564, 0.7706, 0.7132],
        [0.7749, 0.4177, 0.5423, 0.8619],
        [0.5109, 0.3843, 0.4706, 0.9526]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make some random but reproducible tensors

#set the random seed

RANDOM_SEED=21
torch.manual_seed(RANDOM_SEED)
random_tensorC=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensorD=torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)


tensor([[0.4736, 0.6136, 0.0121, 0.0396],
        [0.5674, 0.2538, 0.5338, 0.6093],
        [0.7162, 0.6043, 0.9980, 0.1445]])
tensor([[0.4736, 0.6136, 0.0121, 0.0396],
        [0.5674, 0.2538, 0.5338, 0.6093],
        [0.7162, 0.6043, 0.9980, 0.1445]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Extra resources for reproducibility

* Pytorch docs
* Wikipedia article

## running tensor and pytorch objects on the GPUs(& making faster computation)

GPUs=faster computation on numbers, thanks to CUDA + NVIDIA hardware+ PyTorch working behind the scenes to make everything hunky dory :)

### getting a GPU

1. easiest- Use Google colab for free GPU
2. Use your own GPU- takes a littlt bit of setup requires the investment of setting up GPUs
3. clous computing- GCP, AWS, Azure etc allow to rent computers on cloud and access them.

Refer to pytorch doc to setup ML GPU



### Check for GPU access with PyTorch

In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [ ]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#count numbers of devices
torch.cuda.device_count()

0

## putting tensors (and models) on the GPU

the reason we want our tensors/models on the GPU is because using GPU results in faster computations.

In [ ]:
#create a tensor default on the cpu
tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU(if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])